package org.bastion.core.crypto

import com.google.common.truth.Truth.assertThat
import com.goterl.lazysodium.LazySodiumJava
import com.goterl.lazysodium.SodiumJava
import java.io.File
import java.nio.ByteBuffer
import org.bastion.protocol.v1.Envelope
import org.bastion.protocol.v1.MessageBody
import org.junit.jupiter.api.Test

/**
 * Recomputes every value of `protocol/testvectors/v1.txt` (generated by the Rust crate) with
 * libsodium. Any divergence between the two implementations fails here.
 */
internal class InteropVectorsTest {
    private val sodium: Sodium = TestSodium.instance
    private val v: Map<String, ByteArray> = File(System.getProperty("bastion.vectors"))
        .readLines()
        .filter { it.isNotBlank() && !it.startsWith("#") }
        .associate { line ->
            val (name, value) = line.split(" = ")
            name to requireNotNull(Bytes.fromHex(value)) { name }
        }

    private fun bytes(name: String): ByteArray = requireNotNull(v[name]) { "missing vector $name" }

    private fun int(name: String): Int = ByteBuffer.wrap(bytes(name)).int

    private fun text(name: String): String = String(bytes(name), Charsets.UTF_8)

    private val pcIk = SigningKeypair(sodium, bytes("pc_ik_seed"))
    private val pcXk = ExchangeKeypair(sodium, bytes("pc_xk_secret"), int("pc_xk_epoch"))
    private val pcPk = SigningKeypair(sodium, bytes("pc_pk_seed"))
    private val phoneIk = SigningKeypair(sodium, bytes("phone_ik_seed"))
    private val phoneXk = ExchangeKeypair(sodium, bytes("phone_xk_secret"), int("phone_xk_epoch"))
    private val pc = pcXk.signedBy(pcIk)
    private val phone = phoneXk.signedBy(phoneIk)

    @Test
    fun `hash and transcript encodings`() {
        assertThat(sodium.blake2b(KeySizes.HASH, "abc".toByteArray())).isEqualTo(bytes("blake2b_256_abc"))
        val transcript = Transcript("ctx").field("ab".toByteArray()).u32(7).u64(9).finish()
        assertThat(transcript).isEqualTo(bytes("transcript_example"))
    }

    @Test
    fun `identities and fingerprints`() {
        assertThat(pcIk.publicKey).isEqualTo(bytes("pc_ik_pub"))
        assertThat(pcIk.deviceId).isEqualTo(bytes("pc_device_id"))
        assertThat(pcXk.publicKey).isEqualTo(bytes("pc_xk_pub"))
        assertThat(pc.exchangeSignature).isEqualTo(bytes("pc_xk_sig"))
        assertThat(pc.fingerprint(sodium)).isEqualTo(text("pc_fingerprint"))
        assertThat(pcPk.publicKey).isEqualTo(bytes("pc_pk_pub"))
        assertThat(phoneIk.publicKey).isEqualTo(bytes("phone_ik_pub"))
        assertThat(phoneIk.deviceId).isEqualTo(bytes("phone_device_id"))
        assertThat(phoneXk.publicKey).isEqualTo(bytes("phone_xk_pub"))
        assertThat(phone.exchangeSignature).isEqualTo(bytes("phone_xk_sig"))
        assertThat(phone.fingerprint(sodium)).isEqualTo(text("phone_fingerprint"))
        assertThat(DeviceKeys.fromProto(sodium, pc.toProto())).isEqualTo(pc)
    }

    @Test
    fun `pairing derivations`() {
        val token = bytes("token")
        val wg = bytes("wireguard_pub")
        assertThat(Pairing.tokenHash(sodium, token)).isEqualTo(bytes("token_hash"))
        val proof = Pairing.enrollProof(sodium, token, phone.identity, phone.exchange, wg, pc.identity)
        assertThat(proof).isEqualTo(bytes("enroll_proof"))
        val transcript = Pairing.enrollTranscript(bytes("token_hash"), phone, wg, proof, 1)
        assertThat(transcript).isEqualTo(bytes("enroll_transcript"))
        assertThat(phoneIk.sign(transcript)).isEqualTo(bytes("enroll_signature"))
        val sas = Pairing.sasCode(sodium, token, phone, pc)
        assertThat(sas).isEqualTo(int("sas_code"))
        assertThat(Pairing.formatSas(sas)).isEqualTo(text("sas_display"))
    }

    @Test
    fun `session keys and envelope interoperate`() {
        val pcParty = Party(pc.identity, pc.exchange)
        val phoneParty = Party(phone.identity, phone.exchange)
        val pcToPhone = requireNotNull(Session.directionalKey(sodium, phoneXk, pcParty, phoneParty))
        val phoneToPc = requireNotNull(Session.directionalKey(sodium, phoneXk, phoneParty, pcParty))
        assertThat(pcToPhone.expose()).isEqualTo(bytes("session_pc_to_phone"))
        assertThat(phoneToPc.expose()).isEqualTo(bytes("session_phone_to_pc"))

        val header = EnvelopeHeader(1, pcIk.deviceId, phoneIk.deviceId, pcXk.epoch)
        assertThat(header.aad()).isEqualTo(bytes("envelope_aad"))
        val body = bytes("envelope_body")
        assertThat(EnvelopeCrypto.signatureInput(header.aad(), body)).isEqualTo(bytes("envelope_signature_input"))
        val sealed = EnvelopeCrypto.seal(sodium, pcToPhone, header, pcIk, pcPk, body, bytes("envelope_nonce"))
        assertThat(sealed).isEqualTo(bytes("envelope_bytes"))

        val opened = requireNotNull(
            EnvelopeCrypto.open(
                sodium,
                Envelope.parseFrom(bytes("envelope_bytes")),
                listOf(pcToPhone),
                pc.identity,
                pcPk.publicKey,
            ),
        )
        assertThat(opened.privileged).isTrue()
        val command = MessageBody.parseFrom(opened.body)
        assertThat(command.counter).isEqualTo(42L)
        assertThat(command.command.ring.durationSeconds).isEqualTo(30)
    }

    @Test
    fun `request authentication header`() {
        val header = RequestAuth.sign(
            sodium,
            pcIk,
            text("request_method"),
            text("request_path"),
            ByteBuffer.wrap(bytes("request_timestamp")).long,
            bytes("request_body"),
            bytes("request_nonce"),
        )
        assertThat(header).isEqualTo(text("request_header"))
    }

    @Test
    fun `sealed box made by Rust opens with libsodium`() {
        assertThat(pcXk.openSealed(bytes("sealed_to_pc"))).isEqualTo(bytes("sealed_plaintext"))
        val roundTrip = sodium.seal(pcXk.publicKey, "x".toByteArray())
        assertThat(pcXk.openSealed(roundTrip)).isEqualTo("x".toByteArray())
        assertThat(phoneXk.openSealed(roundTrip)).isNull()
    }
}

internal object TestSodium {
    val instance: Sodium by lazy { LazySodiumAdapter(LazySodiumJava(SodiumJava())) }
}
